### ISSUE TITLE
请教一下，swift 工程如何使用

### ISSUE THREAD

**Issue by SunLn** [danleechina/mixplaintext#2]
是不是将 MixDecrypt.h 文件翻译成对应的 swift 文件，然后 pch 头文件中引入 该文件即可。

原操作
```
添加 MixIosDemo/MixOC/MixDecrypt.h 到您的工程中

在您的 pch 头文件中引入 MixDecrypt.h
```

**Comment by SunLn** [comment]
已经跑通了，只能修改swift项目里面的oc 的文件。我需要再认真看一下你的swift 源码。谢谢。

**Comment by danlee2025** [comment]
不好意思，目前不支持 swift 的源文件。
