### ISSUE TITLE
没太明白这个框架的用法

### ISSUE THREAD

**Issue by XychloveFhy** [danleechina/mixplaintext#4]
我把二进制文件也拖进去了 运行demo 也没看见加密呀

**Comment by houdangdang** [comment]
> 我把二进制文件也拖进去了 运行demo 也没看见加密呀

the same question

**Comment by danlee2025** [comment]
你好，我重新更新了一下 ReadMe，简化了步骤。可以再次看一下。

没有加密可能是因为项目中默认是 Release 模式下才起作用。检查一下是否将其改成 Debug 了。
